name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        go-version: [^1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make codecov
      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./count.out
